// Gridline Tokyo icon set — Nucleo (nucleo-core-outline-32) aliased to the
// lucide names the app already uses, so importing from '@/lib/icons' instead
// of 'lucide-react' swaps the whole icon system with no per-call changes.
// React 19: components re-export directly, no type casts needed. Strokes use
// currentColor, so text-* classes colour them; size/strokeWidth/className/style
// all pass through to the underlying <svg>.
export {
  IconPulseOutline32 as Activity,
  IconCircleWarningOutline32 as AlertCircle,
  IconTriangleWarningOutline32 as AlertTriangle,
  IconArrowDownRightOutline32 as ArrowDownRight,
  IconArrowLeftOutline32 as ArrowLeft,
  IconArrowsOppositeDirectionXOutline32 as ArrowLeftRight,
  IconArrowRightOutline32 as ArrowRight,
  IconArrowsOppositeDirectionXOutline32 as ArrowRightLeft,
  IconArrowUpRightOutline32 as ArrowUpRight,
  IconChartOutline32 as BarChart2,
  IconBellOutline32 as Bell,
  IconBookOpenOutline32 as BookOpen,
  IconChatBotOutline32 as Bot,
  IconSuitcaseOutline32 as Briefcase,
  IconCalendarOutline32 as Calendar,
  IconCameraOutline32 as Camera,
  IconCheckOutline32 as Check,
  IconCircleCheckOutline32 as CheckCircle,
  IconCircleCheck2Outline32 as CheckCircle2,
  IconChevronDownOutline32 as ChevronDown,
  IconChevronLeftOutline32 as ChevronLeft,
  IconChevronRightOutline32 as ChevronRight,
  IconChevronUpOutline32 as ChevronUp,
  IconCircleDollarOutline32 as CircleDollarSign,
  IconClockOutline32 as Clock,
  IconCodeOutline32 as Code2,
  IconCoinsOutline32 as Coins,
  IconCopyOutline32 as Copy,
  IconCreditCardOutline32 as CreditCard,
  IconDatabaseOutline32 as Database,
  IconCurrencyDollarOutline32 as DollarSign,
  IconDownloadOutline32 as Download,
  IconExternalLinkOutline32 as ExternalLink,
  IconEyeOutline32 as Eye,
  IconFileCodeOutline32 as FileCode2,
  IconFileNewOutline32 as FilePlus2,
  IconFilterOutline32 as Filter,
  IconFlagOutline32 as Flag,
  IconGauge2Outline32 as Gauge,
  IconCompareItemsOutline32 as GitCompare,
  IconGlobeOutline32 as Globe,
  IconGlobe2Outline32 as Globe2,
  IconHistoryOutline32 as History,
  IconHouse4Outline32 as Home,
  IconCircleInfoOutline32 as Info,
  IconKeyOutline32 as Key,
  IconBankStatementOutline32 as Landmark,
  IconLayersOutline32 as Layers,
  IconChartLine2Outline32 as LineChart,
  IconSpinnerLoaderOutline32 as Loader2,
  IconLockOutline32 as Lock,
  IconRectLogoutOutline32 as LogOut,
  IconEnvelopeOutline32 as Mail,
  IconMenuOutline32 as Menu,
  IconMessageOutline32 as MessageCircle,
  IconMessage2Outline32 as MessageSquare,
  IconMountainOutline32 as Mountain,
  IconNewspaperOutline32 as Newspaper,
  IconTreePalmOutline32 as Palmtree,
  IconSidebarRightOutline32 as PanelRightOpen,
  IconPenOutline32 as Pencil,
  IconPiggyBankOutline32 as PiggyBank,
  IconMediaPlayOutline32 as Play,
  IconCircleMediaPlayOutline32 as PlayCircle,
  IconPlugOutline32 as Plug,
  IconPlusOutline32 as Plus,
  IconCirclePlusOutline32 as PlusCircle,
  IconRadioOutline32 as Radio,
  IconRefreshOutline32 as RefreshCw,
  IconRotateOutline32 as RotateCcw,
  IconFloppyDiskOutline32 as Save,
  IconMagnifierOutline32 as Search,
  IconPaperPlaneOutline32 as Send,
  IconGearOutline32 as Settings,
  IconShieldOutline32 as Shield,
  IconSailboatOutline32 as Ship,
  IconBagOutline32 as ShoppingBag,
  IconSparkleOutline32 as Sparkles,
  IconCheckboxUncheckedOutline32 as Square,
  IconStarOutline32 as Star,
  IconStoreOutline32 as Store,
  IconTargetOutline32 as Target,
  IconTelescopeOutline32 as Telescope,
  IconConsoleOutline32 as Terminal,
  IconThumbsDownOutline32 as ThumbsDown,
  IconThumbsUpOutline32 as ThumbsUp,
  IconTrashOutline32 as Trash,
  IconTrash2Outline32 as Trash2,
  IconArrowTrendDownOutline32 as TrendingDown,
  IconArrowTrendUpOutline32 as TrendingUp,
  IconTrophyOutline32 as Trophy,
  IconUndoOutline32 as Undo2,
  IconUserOutline32 as User,
  IconUsersOutline32 as Users,
  IconWalletOutline32 as Wallet,
  IconWrenchOutline32 as Wrench,
  IconXmarkOutline32 as X,
  // executor-specific
  IconKey2Outline32 as KeyRound,
  IconLaptopOutline32 as Laptop,
  IconGrid2Outline32 as LayoutDashboard,
  IconLink2Outline32 as Link2,
  IconMoonOutline32 as Moon,
  IconPaletteOutline32 as Palette,
  IconMediaPauseOutline32 as Pause,
  IconChartPieOutline32 as PieChart,
  IconSunOutline32 as Sun,
  IconTestTubeOutline32 as TestTube,
  IconWifiOutline32 as Wifi,
  IconWifiOffOutline32 as WifiOff,
  IconCircleXmarkOutline32 as XCircle,
} from 'nucleo-core-outline-32';

// Icon component type compatible with the Nucleo components above and the
// former lucide call sites (both are SVG components taking className/size).
// Keeps `import { type LucideIcon } from '@/lib/icons'` resolving so the
// `icon: LucideIcon` props (nav config, EmptyState, …) accept Nucleo icons.
import type { FC } from 'react';
export type LucideIcon = FC<{ className?: string; size?: number | string }>;
